### ISSUE TITLE
Please release official gem

### ISSUE THREAD

**Issue by johnnyshields** [Polarion/mongoid_relations_dirty_tracking#2]
Hi, seems like this gem isn't released to RubyGems yet. I've been using it in production. Would appreciate if you can cut a release. I recommend `gem-release` gem.

**Comment by davidsevcik** [comment]
Hi. I have just published it in the version 0.1.0

**Comment by johnnyshields** [comment]
Cheers, I appreciate it. Congrats on releasing a new gem into the wild!
